x = int(input("Enter first number: "))
y = float(input("Enter second number: "))
z = complex(input("Enter third number: "))

print("Integer value is:", x)
print("Data Type of x is:", type(x))
print("Float value is:", y)
print("Data Type of y is:", type(y))
print("Complex value is:", z)
print("Data Type of z is:", type(z))